set(PACKAGE_VERSION "@OSH_MAJOR@.@OSH_MINOR@.@OSH_PATCH@")
if("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "@OSH_MAJOR@")
  set(PACKAGE_VERSION_COMPATIBLE 1)
  if("${PACKAGE_FIND_VERSION_MINOR}" EQUAL "@OSH_MINOR@" AND
     "${PACKAGE_FIND_VERSION_PATCH}" EQUAL "@OSH_PATCH@")
    set(PACKAGE_VERSION_EXACT 1)
  endif()
endif()
