void refine_domain_interiors(
    Mesh& mesh,
    Int dim,
    LOs keys2edges,
    LOs keys2midverts,
    LOs old_verts2new_verts,
    LOs& keys2cuts,
    LOs& keys2pairs,
    LOs& cut_verts2verts,
    LOs& pair_verts2verts);

void combine_pairs_and_cuts(
    Int ent_dim,
    LOs keys2cuts,
    LOs keys2pairs_last,
    LOs cut_verts2verts,
    LOs pair_verts2verts_last,
    LOs& keys2prods,
    LOs& prod_verts2verts);
