/* This file was auto-generated by
   gen_Omega_h_chartab */

#ifndef OMEGA_H_CHARTAB_HPP
#define OMEGA_H_CHARTAB_HPP

namespace Omega_h {

enum { NCHARS = 98 };

extern int const chartab[128];
extern char const inv_chartab[NCHARS];

}  // end namespace Omega_h

#endif
