/* This file was auto-generated by
   gen_chartab */

#ifndef OMEGA_H_CHARTAB_HPP
#define OMEGA_H_CHARTAB_HPP

namespace Omega_h {

enum { NCHARS = 98 };

#define OMEGA_H_CHARTAB_SIZE 128
extern int const chartab[OMEGA_H_CHARTAB_SIZE];
extern char const inv_chartab[NCHARS];

}  // end namespace Omega_h

#endif
