if(DETECT_KOKKOS_OPTS)
  return()
endif()
set(DETECT_KOKKOS_OPTS true)

function(detect_kokkos_opts)
  if (Kokkos_FOUND)
    foreach(DEVICE IN LISTS Kokkos_DEVICES)
      if("${DEVICE}" MATCHES "CUDA")
        message(STATUS "Kokkos has CUDA")
        set(Kokkos_HAS_CUDA TRUE PARENT_SCOPE)
      endif()
      if("${DEVICE}" MATCHES "OPENMP")
        message(STATUS "Kokkos has OpenMP")
        set(Kokkos_HAS_OpenMP TRUE PARENT_SCOPE)
      endif()
    endforeach()
    foreach(OPT IN LISTS Kokkos_OPTIONS)
      if("${OPT}" MATCHES "PROFILING")
        message(STATUS "Kokkos has profiling")
        set(Kokkos_HAS_PROFILING TRUE PARENT_SCOPE)
      endif()
      if("${OPT}" MATCHES "CUDA_LAMBDA")
        message(STATUS "Kokkos has CUDA lambdas")
        set(Kokkos_HAS_CUDA_LAMBDA TRUE PARENT_SCOPE)
      endif()
    endforeach()
  endif()
endfunction(detect_kokkos_opts)
